### ISSUE TITLE
Add a license (copyleft)

### ISSUE THREAD

**Issue by benjifisher** [chrisfromredfin/dcon21-milb#1]
I think we could borrow some of the code from the custom process plugin in this project and add it to the `layout_builder` module in Drupal core.

I would be more comfortable with the borrowing step if this project were explicitly licensed under GPL, like the rest of Drupal.

There is already an issue [Layout Builder Destination Plugin for Migrate API](https://www.drupal.org/project/drupal/issues/3087210) for Drupal core, but I think that a process plugin is what we need, not a destination plugin.

**Comment by chrisfromredfin** [comment]
GPL v2 added to repo.

**Comment by benjifisher** [comment]
Thanks!
